### PR TITLE
#5 Completed Part 4 of the tutorial

### PR DESCRIPTION
**Pull request by louisevdb84**

### CODE REVIEW

**Comment by atherdon** [comment]
You can go to next chapter - i'll check your code updates a bit later.
Btw, how do you feeling?

**Comment by louisevdb84** [comment]
Cool, thanks. 
Feeling very tired all the time with all sorts of aches and pains. Went for monthly checkup today and fortunately everything is still fine :).

**Comment by atherdon** [comment]
it's a good news. I'm feeling connected to this awesome Event - this is why i'm worried too.
But i think at current point we have a very advanced tech and doctors with skills so i think everything will be great. So take more rest that usually start preparing to have a lot of fun soon :)

First daughter of my friend is going to school at September - times flying so fast...

**Comment by louisevdb84** [comment]
Yeah, I agree, we have very skilled doctors and the hospital where I'm going is great.  So I'm not very stressed about that. 

Cant wait though! :) He should be born anytime between 2 July - 14 July. Not that long to go anymore. My husband is taking 2 weeks leave to help me out. His parents live in Netherlands and they will only be able to come to South Africa end of August to visit us. My parents live 2 hours drive from us. They will also try to help out as much as they can, but its difficult with everyone living so far apart.

**Pull request merged**
